---
Components:
- name: comp1
  file: data/comp1.csv
  nproc_restriction:
  #[48, 96, 144, 192, 240, 288, 336, 384, 432, 480, 528, 576, 624,672, 720, 768, 816, 864, 912, 960, 1008 ]
  timestep_info:
  timestep_nproc:

- name: comp2
  file: data/comp2.csv
  nproc_restriction:
  timestep_info: 
  timestep_nproc:

#- name: comp3
#  file: data/comp3.csv
#  nproc_restriction:
#  timestep_info:
#  timestep_nproc:


General:
  max_nproc: 2000
  TTS_ratio: .5
  interpo_method: quadratic
  show_plots: False
  nproc_step: 24
